Chapter4/Supplementary/proc_hom/config/routes.rb
ProcHom::Application.routes.draw do

  
  resources :blo_runs
  resources :gene_blo_runs
 

  root :to => "welcome#index"

  
  scope '/proc_hom' do
   root :to => 'welcome#index'
  end
  
  
end

Chapter4/Supplementary/proc_hom/app/models/all_gene.rb
class AllGene < ActiveRecord::Base
end

Chapter4/Supplementary/proc_hom/app/models/blo_run.rb
class BloRun < ActiveRecord::Base
end

Chapter4/Supplementary/proc_hom/app/models/color.rb
class Color < ActiveRecord::Base
  belongs_to :color_scheme
  has_many :prok_group
end

Chapter4/Supplementary/proc_hom/app/models/fen_stage.rb
class FenStage < ActiveRecord::Base
  belongs_to :prev_fen_stage
  attr_accessible :calc_section, :phylo_prog, :timing_prog
end

Chapter4/Supplementary/proc_hom/app/models/gene.rb
class Gene < ActiveRecord::Base
  has_many :gene_seqs
  has_many :gene_seq_clusters
  has_many :gene_ortho_runs
  has_many :hgt_par_fragms
  has_many :hgt_par_contins

end

Chapter4/Supplementary/proc_hom/app/models/gene_blo_run.rb
class GeneBloRun < ActiveRecord::Base
  belongs_to :gene
  belongs_to :blo_run
end

Chapter4/Supplementary/proc_hom/app/models/gene_seq.rb
class GeneSeq < ActiveRecord::Base
  belongs_to :gene
end

Chapter4/Supplementary/proc_hom/app/models/hgt_detect.rb
class HgtDetect < ActiveRecord::Base
  #attr_accessible :dest_id, :rank, :source_id, :value
end

Chapter4/Supplementary/proc_hom/app/models/hgt_obj.rb
class HgtObj < ActiveRecord::Base
  # attr_accessible :title, :body
end

Chapter4/Supplementary/proc_hom/app/models/hgt_obj_all.rb
class HgtObjAll < ActiveRecord::Base
  attr_accessible :dest_id, :source_id
end

Chapter4/Supplementary/proc_hom/app/models/hgt_obj_neg.rb
class HgtObjNeg < ActiveRecord::Base
  attr_accessible :dest_id, :source_id
end

Chapter4/Supplementary/proc_hom/app/models/hgt_qfunc.rb
class HgtQfunc < ActiveRecord::Base
  #attr_accessible :dest_id, :rank, :source_id, :value
end

Chapter4/Supplementary/proc_hom/app/models/mrca.rb
class Mrca < ActiveRecord::Base
  has_many :mrca_prok_group
end

Chapter4/Supplementary/proc_hom/app/models/mrca_stdev.rb
class MrcaStdev < ActiveRecord::Base
  belongs_to :mrca
  # attr_accessible :title, :body
end

Chapter4/Supplementary/proc_hom/app/models/msa_run.rb
class MsaRun < ActiveRecord::Base
end

Chapter4/Supplementary/proc_hom/app/models/ncbi_seq.rb
class NcbiSeq < ActiveRecord::Base
  
 #belongs_to :taxon_group, :class_name => "TaxonGroup", :foreign_key => :taxon_id
 
 belongs_to :taxon
 
 #has_one :gene_blo_seq, :class_name => "GeneBloSeq", :foreign_key => :ncbi_seq_id
 
 has_one :gene_blo_seq
 
end

Chapter4/Supplementary/proc_hom/app/models/ortho_run.rb
class OrthoRun < ActiveRecord::Base
 has_many :gene_ortho_runs

end

Chapter4/Supplementary/proc_hom/app/models/prok_group.rb
class ProkGroup < ActiveRecord::Base
  
  belongs_to :color
  has_many :taxon_group
  
  #return an array with the prok_group_id identifiers of the selected criterium
  def self.ids_for_crit(crit)
    
    pgs = GroupCriter.find_by_name(crit).prok_group.order('order_id asc').select('id')
    pgs_arr = pgs.collect {|pg| pg.id}
    
    return pgs_arr
    
    
    
    
    
    
  end
  
end

Chapter4/Supplementary/proc_hom/app/models/sequence.rb
class Sequence < ActiveRecord::Base
  
    
end

Chapter4/Supplementary/proc_hom/app/models/taxon.rb
class Taxon < ActiveRecord::Base
  belongs_to :parent
  belongs_to :division
  
  has_many :ncbi_seq
  
  
  has_many :taxon_group #, :class_name => "TaxonGroup", :foreign_key => "id" 
  
  has_one :ncbi_seqs_taxon
  
end

Chapter4/Supplementary/proc_hom/app/models/tree_hgt.rb
class TreeHgt < ActiveRecord::Base
end

Chapter4/Supplementary/proc_hom/app/controllers/gene_blo_runs_controller.rb
class GeneBloRunsController < ApplicationController
  # GET /gene_blo_runs
  # GET /gene_blo_runs.json
  def index
    @gene_blo_runs = GeneBloRun.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @gene_blo_runs }
    end
  end

  # GET /gene_blo_runs/1
  # GET /gene_blo_runs/1.json
  def show
    @gene_blo_run = GeneBloRun.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @gene_blo_run }
      format.fasta { send_file "/root/devel/proc_hom/files/proc/gene_blo_runs/#{@gene_blo_run.gene.name}.fasta", :type => 'text/plain', :disposition => 'inline' }
    end
  end

  # GET /gene_blo_runs/new
  # GET /gene_blo_runs/new.json
  def new
    @gene_blo_run = GeneBloRun.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @gene_blo_run }
    end
  end

  # GET /gene_blo_runs/1/edit
  def edit
    @gene_blo_run = GeneBloRun.find(params[:id])
  end

  # POST /gene_blo_runs
  # POST /gene_blo_runs.json
  def create
    @gene_blo_run = GeneBloRun.new(params[:gene_blo_run])

    respond_to do |format|
      if @gene_blo_run.save
        format.html { redirect_to @gene_blo_run, :notice => 'Gene blo run was successfully created.' }
        format.json { render :json => @gene_blo_run, :status => :created, :location => @gene_blo_run }
      else
        format.html { render :action => "new" }
        format.json { render :json => @gene_blo_run.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /gene_blo_runs/1
  # PUT /gene_blo_runs/1.json
  def update
    @gene_blo_run = GeneBloRun.find(params[:id])

    respond_to do |format|
      if @gene_blo_run.update_attributes(params[:gene_blo_run])
        format.html { redirect_to @gene_blo_run, :notice => 'Gene blo run was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @gene_blo_run.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /gene_blo_runs/1
  # DELETE /gene_blo_runs/1.json
  def destroy
    @gene_blo_run = GeneBloRun.find(params[:id])
    @gene_blo_run.destroy

    respond_to do |format|
      format.html { redirect_to :controller => 'gene_blo_runs', :action => 'index'  }
      format.json { head :ok }
    end
  end
end

Chapter4/Supplementary/proc_hom/app/helpers/gene_blo_runs_helper.rb
module GeneBloRunsHelper
end

Chapter4/Supplementary/proc_hom/app/views/gene_blo_runs/_form.html.erb
<%= form_for(@gene_blo_run) do |f| %>
  <% if @gene_blo_run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gene_blo_run.errors.count, "error") %> prohibited this gene_blo_run from being saved:</h2>

      <ul>
      <% @gene_blo_run.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gene %><br />
    <%= f.text_field :gene %>
  </div>
  <div class="field">
    <%= f.label :blo_run %><br />
    <%= f.text_field :blo_run %>
  </div>
  <div class="field">
    <%= f.label :oa_length %><br />
    <%= f.number_field :oa_length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Chapter4/Supplementary/proc_hom/app/views/gene_blo_runs/edit.html.erb
<h1>Editing gene_blo_run</h1>

<%= render 'form' %>

<%= link_to 'Show', @gene_blo_run %> |
<%= link_to 'Back', gene_blo_runs_path %>

Chapter4/Supplementary/proc_hom/app/views/gene_blo_runs/index.html.erb
<h1>Listing gene_blo_runs</h1>

<table>
  <tr>
    <th>Gene</th>
    <th>Blo run</th>
    <th>Oa length</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gene_blo_runs.each do |gene_blo_run| %>
  <tr>
    <td><%= gene_blo_run.gene.name %></td>
    <td><%= gene_blo_run.blo_run.params %></td>
    <td><%= gene_blo_run.oa_length %></td>
    <td><%= link_to 'Show', "#{ENV['RAILS_RELATIVE_URL_ROOT']}/#{gene_blo_run}" %></td>
    <td><%= link_to 'Test', "gene_blo_runs/#{gene_blo_run.to_param}" %></td>
    <td><%= link_to 'Test2', "gene_blo_runs" %></td>
    <td><%=  "gene_blo_runs/#{gene_blo_run.to_param}" %></td>
    <td><%=  gene_blo_runs_url(gene_blo_run) %></td>

    <td><%= link_to 'Relative_url',  "#{ENV['RAILS_RELATIVE_URL_ROOT']}, #{ActionController::Base.config.relative_url_root}" %></td>

    <td><%= "ok" %></td>

    
    <td><%= link_to 'Edit', edit_gene_blo_run_path(gene_blo_run) %></td>
    <td><%= link_to 'Destroy', "gene_blo_runs/#{gene_blo_run.to_param}" , :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gene blo run', new_gene_blo_run_path %>

Chapter4/Supplementary/proc_hom/app/views/gene_blo_runs/new.html.erb
<h1>New gene_blo_run</h1>

<%= render 'form' %>

<%= link_to 'Back', gene_blo_runs_path %>

Chapter4/Supplementary/proc_hom/app/views/gene_blo_runs/original_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gene:</b>
  <%= @gene_blo_run.gene %>
</p>

<p>
  <b>Blo run:</b>
  <%= @gene_blo_run.blo_run %>
</p>

<p>
  <b>Oa length:</b>
  <%= @gene_blo_run.oa_length %>
</p>


<%= link_to 'Edit', edit_gene_blo_run_path(@gene_blo_run) %> |
<%= link_to 'Back', gene_blo_runs_path %>

Chapter4/Supplementary/proc_hom/app/views/gene_blo_runs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gene:</b>
  <%= @gene_blo_run.gene %>
</p>

<p>
  <b>Blo run:</b>
  <%= @gene_blo_run.blo_run %>
</p>

<p>
  <b>Oa length:</b>
  <%= @gene_blo_run.oa_length %>
</p>


<%= link_to 'Edit', edit_gene_blo_run_path(@gene_blo_run) %> |
<%= link_to 'Back', gene_blo_runs_path %>