Chapter4/Supplementary/proc_hom/config/routes.rb
ProcHom::Application.routes.draw do

  
  resources :blo_runs
  resources :gene_blo_runs
 

  root :to => "welcome#index"

  
  scope '/proc_hom' do
   root :to => 'welcome#index'
  end
  
  
end

Chapter4/Supplementary/proc_hom/app/models/all_gene.rb
class AllGene < ActiveRecord::Base
end

Chapter4/Supplementary/proc_hom/app/models/blo_run.rb
class BloRun < ActiveRecord::Base
end

Chapter4/Supplementary/proc_hom/app/models/color.rb
class Color < ActiveRecord::Base
  belongs_to :color_scheme
  has_many :prok_group
end

Chapter4/Supplementary/proc_hom/app/models/fen_stage.rb
class FenStage < ActiveRecord::Base
  belongs_to :prev_fen_stage
  attr_accessible :calc_section, :phylo_prog, :timing_prog
end

Chapter4/Supplementary/proc_hom/app/models/gene.rb
class Gene < ActiveRecord::Base
  has_many :gene_seqs
  has_many :gene_seq_clusters
  has_many :gene_ortho_runs
  has_many :hgt_par_fragms
  has_many :hgt_par_contins

end

Chapter4/Supplementary/proc_hom/app/models/gene_seq.rb
class GeneSeq < ActiveRecord::Base
  belongs_to :gene
end

Chapter4/Supplementary/proc_hom/app/models/hgt_detect.rb
class HgtDetect < ActiveRecord::Base
  #attr_accessible :dest_id, :rank, :source_id, :value
end

Chapter4/Supplementary/proc_hom/app/models/hgt_obj.rb
class HgtObj < ActiveRecord::Base
  # attr_accessible :title, :body
end

Chapter4/Supplementary/proc_hom/app/models/hgt_obj_all.rb
class HgtObjAll < ActiveRecord::Base
  attr_accessible :dest_id, :source_id
end

Chapter4/Supplementary/proc_hom/app/models/hgt_obj_neg.rb
class HgtObjNeg < ActiveRecord::Base
  attr_accessible :dest_id, :source_id
end

Chapter4/Supplementary/proc_hom/app/models/hgt_par_fen.rb
class HgtParFen < ActiveRecord::Base
  belongs_to :gene
  #attr_accessible :fen_idx_max, :fen_idx_min, :fen_no, :win_size
end

Chapter4/Supplementary/proc_hom/app/models/hgt_qfunc.rb
class HgtQfunc < ActiveRecord::Base
  #attr_accessible :dest_id, :rank, :source_id, :value
end

Chapter4/Supplementary/proc_hom/app/models/mrca.rb
class Mrca < ActiveRecord::Base
  has_many :mrca_prok_group
end

Chapter4/Supplementary/proc_hom/app/models/mrca_stdev.rb
class MrcaStdev < ActiveRecord::Base
  belongs_to :mrca
  # attr_accessible :title, :body
end

Chapter4/Supplementary/proc_hom/app/models/msa_run.rb
class MsaRun < ActiveRecord::Base
end

Chapter4/Supplementary/proc_hom/app/models/ncbi_seq.rb
class NcbiSeq < ActiveRecord::Base
  
 #belongs_to :taxon_group, :class_name => "TaxonGroup", :foreign_key => :taxon_id
 
 belongs_to :taxon
 
 #has_one :gene_blo_seq, :class_name => "GeneBloSeq", :foreign_key => :ncbi_seq_id
 
 has_one :gene_blo_seq
 
end

Chapter4/Supplementary/proc_hom/app/models/ortho_run.rb
class OrthoRun < ActiveRecord::Base
 has_many :gene_ortho_runs

end

Chapter4/Supplementary/proc_hom/app/models/prok_group.rb
class ProkGroup < ActiveRecord::Base
  
  belongs_to :color
  has_many :taxon_group
  
  #return an array with the prok_group_id identifiers of the selected criterium
  def self.ids_for_crit(crit)
    
    pgs = GroupCriter.find_by_name(crit).prok_group.order('order_id asc').select('id')
    pgs_arr = pgs.collect {|pg| pg.id}
    
    return pgs_arr
    
    
    
    
    
    
  end
  
end

Chapter4/Supplementary/proc_hom/app/models/sequence.rb
class Sequence < ActiveRecord::Base
  
    
end

Chapter4/Supplementary/proc_hom/app/models/taxon.rb
class Taxon < ActiveRecord::Base
  belongs_to :parent
  belongs_to :division
  
  has_many :ncbi_seq
  
  
  has_many :taxon_group #, :class_name => "TaxonGroup", :foreign_key => "id" 
  
  has_one :ncbi_seqs_taxon
  
end

Chapter4/Supplementary/proc_hom/app/models/tree_hgt.rb
class TreeHgt < ActiveRecord::Base
end

Chapter4/Supplementary/proc_hom/app/controllers/blo_runs_controller.rb
class BloRunsController < ApplicationController
  # GET /blo_runs
  # GET /blo_runs.json
  def index
    @blo_runs = BloRun.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @blo_runs }
    end
  end


 #send_file "/root/devel/proc_hom/files/proc/gene_blo_runs/#{@blo_run.name}.fasta", :type => 'text/html'

  # GET /blo_runs/1
  # GET /blo_runs/1.json
  def show
    @blo_run = BloRun.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :text => @blo_run.id }
      format.fasta { render :text => "fasta ok"  }
    end
  end

 
  # GET /blo_runs/new
  # GET /blo_runs/new.json
  def new
    @blo_run = BloRun.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @blo_run }
    end
  end

  # GET /blo_runs/1/edit
  def edit
    @blo_run = BloRun.find(params[:id])
  end

  # POST /blo_runs
  # POST /blo_runs.json
  def create
    @blo_run = BloRun.new(params[:blo_run])

    respond_to do |format|
      if @blo_run.save
        format.html { redirect_to @blo_run, :notice => 'Blo run was successfully created.' }
        format.json { render :json => @blo_run, :status => :created, :location => @blo_run }
      else
        format.html { render :action => "new" }
        format.json { render :json => @blo_run.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blo_runs/1
  # PUT /blo_runs/1.json
  def update
    @blo_run = BloRun.find(params[:id])

    respond_to do |format|
      if @blo_run.update_attributes(params[:blo_run])
        format.html { redirect_to @blo_run, :notice => 'Blo run was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @blo_run.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blo_runs/1
  # DELETE /blo_runs/1.json
  def destroy
    @blo_run = BloRun.find(params[:id])
    @blo_run.destroy

    respond_to do |format|
      format.html { redirect_to blo_runs_url }
      format.json { head :ok }
    end
  end
end

Chapter4/Supplementary/proc_hom/app/helpers/blo_runs_helper.rb
module BloRunsHelper
end

Chapter4/Supplementary/proc_hom/app/views/blo_runs/_form.html.erb
<%= form_for(@blo_run) do |f| %>
  <% if @blo_run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blo_run.errors.count, "error") %> prohibited this blo_run from being saved:</h2>

      <ul>
      <% @blo_run.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :params %><br />
    <%= f.text_field :params %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Chapter4/Supplementary/proc_hom/app/views/blo_runs/edit.html.erb
<h1>Editing blo_run</h1>

<%= render 'form' %>

<%= link_to 'Show', @blo_run %> |
<%= link_to 'Back', blo_runs_path %>

Chapter4/Supplementary/proc_hom/app/views/blo_runs/index.html.erb
<h1>Listing blo_runs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Params</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blo_runs.each do |blo_run| %>
  <tr>
    <td><%= blo_run.name %></td>
    <td><%= blo_run.params %></td>
    <td><%= link_to 'Show', gene_blo_runs_path %></td>
    <td><%= link_to 'show url', "blo_runs/0" %></td>
    <td><%= link_to 'Edit', edit_blo_run_path(blo_run) %></td>
    <td><%= link_to 'Destroys', "gene_blo_runs/#{blo_run.to_param}" , :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blo run', new_blo_run_path %>

Chapter4/Supplementary/proc_hom/app/views/blo_runs/new.html.erb
<h1>New blo_run</h1>

<%= render 'form' %>

<%= link_to 'Back', blo_runs_path %>

Chapter4/Supplementary/proc_hom/app/views/blo_runs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @blo_run.name %>
</p>

<p>
  <b>Params:</b>
  <%= @blo_run.params %>
</p>


<%= link_to 'Edit', edit_blo_run_path(@blo_run) %> |
<%= link_to 'Back', blo_runs_path %>